version: '3.4'

services:
  pedido.ui:
    build:
      context: .
      dockerfile: src/Pedido.Ui/Dockerfile
    depends_on:
      - db
    networks:
      - common_network
    
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_PID=Express
    restart: unless-stopped
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - common_network

volumes:
  db-data:

networks:
  common_network:
